version: '3'

services:
  app:
    container_name: docker-node-mongo
    build: .
    command: npm start
    ports: 
      - '3000:3000'
    links:
      - mongo
    volumes: 
      - .:/usr/app
  mongo: 
    container_name: mongo
    image: mongo
    ports: 
      - '27017:27017'